### ISSUE TITLE
Player ranged attack

### ISSUE THREAD

**Issue by ItaiYavin** [KasperHdL/OOSE2015#10]
Give player a ranged attack function

Create a projectile.

**Comment by KasperHdL** [comment]
Yaaay

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=7.1.2]
On Tue, Apr 21, 2015 at 23:20, KasperHdL/OOSE2015
reply@reply.github.com
wrote:
Closed #10 [https://github.com/KasperHdL/OOSE2015/issues/10] .

—
Reply to this email directly or view it on GitHub
[https://github.com/KasperHdL/OOSE2015/issues/10#event-286647458] .[https://github.com/notifications/beacon/ABtO03Iw4SmFBx-KJMBvjEsNCNgeFOsCks5oBraGgaJpZM4D8fye.gif]
